$inherits:
  from: 'tasks/builds/b2g_emulator_x86_base.yml'
  variables:
    build_name: 'emulator-x86-kk'
    build_type: 'opt'
task:
  workerType: emualtor-x86-kk
  scopes:
    - 'docker-worker:cache:workspace-emulator-kk-x86-opt'
    - 'docker-worker:cache:workspace-emulator-kk-x86-opt-objdir-gecko-{{project}}'
  metadata:
    name: '[TC] B2G KK X86 Emulator (Opt)'

  extra:
    treeherderEnv:
      - staging
    treeherder:
      # Disable "TC" prefix...
      machine:
        platform: b2g-emu-kk

  payload:
    cache:
      workspace-emulator-kk-x86-opt: /home/worker/workspace
      workspace-emulator-kk-x86-opt-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-x86-kk'
